import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChevronDown } from "lucide-react";

import { FloatingNav } from "@/components/ui/floating-navbar";
import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
          <FloatingNav navItems={[
            { name: "Home", link: "/" },
            { name: "Products", link: "/products", icon: <><ChevronDown /></> },
            { name: "Resources", link: "/resources", icon: <><ChevronDown /></> },
            { name: "Pricing", link: "/pricing" },
          ]} />
          {children}
        </main>
      </body>
    </html>
  );
}
